#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_dev`. 
#
if [ ! -z "$1" ] && [ -s "$TB/$1" ]; then
  cd "$TB/$1"
else
  cd "$PROJECTS/$1"
fi
