execute pathogen#infect()
source ~/.vim/bundles.vim 
source ~/.vim/global.vim   
source ~/.vim/plugins.vim 
source ~/.vim/macros.vim
source ~/.vim/before.vim  

Bundle 'derekwyatt/vim-scala'

let g:neocomplcache_enable_at_startup = 1
let macvim_skip_colorscheme=1
set runtimepath^=~/.vim/bundle/ctrlp.vim
